
app_path : 'C:\Users\zsomb\PycharmProjects\ecg_reporter\ecg_reporter'
images_path: 'C:\Users\zsomb\PycharmProjects\ecg_reporter\ecg_reporter\images'

#app_path: '/home/pi/db_report/poreporter'
#input_files_path: '/home/ec2-user/db_report/poreporter/files/input_files'

db:
    host: 'localhost'
    port: '5432'
    dbname: 'postgres'
    username: 'postgres'
    password: 'postgres'
