# Windows
app_path : 'C:\Users\zsomb\PycharmProjects\ecg_reporter\ecg_reporter'
images_path: 'C:\Users\zsomb\PycharmProjects\ecg_reporter\ecg_reporter\images'
pdf_path: 'C:\Users\zsomb\PycharmProjects\ecg_reporter\ecg_reporter\pdf'

# Linux
#app_path: '/home/pi/software/ecg_reporter'
#images_path: '/home/pi/software/ecg_reporter/images'
#pdf_path: '/home/pi/software/ecg_reporter/pdf'

# Email sending
from_address: 'gyhome.reporter@gmail.com'
to_address: 'zsomborjoel@gmail.com'

# Database
db:
    host: 'localhost'
    port: '5432'
    dbname: 'postgres'
    username: 'postgres'
    password: 'postgres'
